version: 2
jobs:
  swc-config:
    docker:
      - image: circleci/node:8.11.1
    steps:
      - checkout
      - run:
          name: Validate SWC yaml config and generate swc-definition.json
          command:  |
            git config --global user.email "$GIT_USER@users.noreply.github.com"
            git config --global user.name "$GIT_USER"
            echo "machine github.com login $GIT_USER password $GITHUB_TOKEN" > ~/.netrc
            cd scripts && yarn && yarn run schema-validation && yarn run updateswc
            cd ../
            command=$(git status|grep -c 'swc-definition.json')
            if ((command > 0)); then
              git add export/
              git commit -m "Update SWC definition [ci skip]"
              git push -q https://${GIT_TOKEN}@github.com/${GIT_ORGANIZATION}/SWC-registry.git master
            fi

  deploy-website:
    docker:
      - image: circleci/node:8.11.1
    steps:
      - checkout
      - run:
          name: Deploying to GitHub Pages
          command: |
            git config --global user.email "$GIT_USER@users.noreply.github.com"
            git config --global user.name "$GIT_USER"
            echo "machine github.com login $GIT_USER password $GITHUB_TOKEN" > ~/.netrc
            cd website && yarn install && npm run content && GIT_USER=$GIT_USER yarn run publish-gh-pages

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy-website:
          filters:
            branches:
              only: website
              ignore: gh-pages
      - swc-config:
          filters:
            branches:
              only: master
